spring:
  transaction:
    rollback-on-commit-failure: true
  aop:
    auto: true
    proxy-target-class: true
  datasource:
    druid:
      master:
        url: jdbc:mysql://192.168.1.100:3306/dynamic_mall?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: root
        initial-size: 2
      slave:
        url: jdbc:mysql://192.168.1.100:3306/dynamic_mall?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
        username: root
        password: root
        initial-size: 4
      aop-patterns: cn.mmooo.dao.*
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: cn.mmooo.model


mapper:
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql

logging:
  level:
    root: info
    cn.mmooo: debug
